# Generated by Django 5.0 on 2024-08-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.IntegerField(default=180)),
                ('count', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctoring.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctoring.student')),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('student_id', 'assessment_id')},
            },
        ),
    ]
