# Generated by Django 5.0 on 2024-08-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='count',
            new_name='active_count',
        ),
    ]
